language: rust
os:
- linux
- osx
rust:
- nightly
- stable
matrix:
  allow_failures:
  - os: linux
    rust: nightly
  - os: osx
    rust: nightly
before_install:
- '[ "$TRAVIS_OS_NAME" = linux ] && sudo apt-get update -qq || brew update'
install:
- '[ "$TRAVIS_OS_NAME" = linux ] && sudo apt-get install -y libsdl2-dev libegl1-mesa-dev libgles2-mesa-dev llvm-dev libclang-dev clang || brew install sdl2 llvm'
script:
- '[ "$TRAVIS_OS_NAME" = osx ] && export PATH="/usr/local/opt/llvm/bin:$PATH" && export LIBCLANG_PATH="/usr/local/opt/llvm/bin"'
- 'if [[ "$TRAVIS_OS_NAME" == linux ]]; then wget -O - https://www.libsdl.org/release/SDL2-2.0.12.tar.gz | tar xz; fi'
- 'if [[ "$TRAVIS_OS_NAME" == linux ]]; then (cd SDL2-* && ./configure --prefix=$HOME/.local && make -j 3 install); fi'
- 'if [[ "$TRAVIS_OS_NAME" == linux ]]; then export PATH=~/.local/bin:$PATH; export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig"; fi'
- pushd tcod_sys; cargo build --features generate_bindings; cat $TARGET_bindings.rs; popd
- cargo build --verbose
- cargo test --verbose
- cargo test --features "rustc-serialize serde" --verbose
- cargo test --release
after_success: ! '[ $TRAVIS_BRANCH = master ] &&

  [ "$TRAVIS_OS_NAME" = linux ] &&

  [ $TRAVIS_PULL_REQUEST = false ] &&

  cargo doc &&

  echo ''<meta http-equiv=refresh content="0;url=tcod/index.html">'' > target/doc/index.html
  &&

  git config --global user.email "travis@travis-ci.org" &&

  git config --global user.name "travis-ci" &&

  sudo pip install ghp-import &&

  ghp-import -n target/doc &&

  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

'
env:
  global:
  - secure: h21kqC5s6iVs4p5n9KFZ5ZTWtPF8nGVFpaPP6t/1Sg+xMaHMDyr/sBYI1gsNGTXrVsiP2Zs6cRTBEbX12PVL6MXFgKpdhKG1+lBCMk6HxU8/W2UHCh6Y38+W4Ybyv5fuoWqkUOX3yODNkRZWrqNhdm8lCdE2uGczkIKPi7hDYMM=
